@if "%1"=="" goto TARGET_ROOT_ARG_NOT_TAKEN
@goto TARGET_ROOT_ARG_TAKEN

:TARGET_ROOT_ARG_NOT_TAKEN
@set TARGET_ROOT=%DEF_TARGET_ROOT%
@goto TARGET_ROOT_IS_SET

:TARGET_ROOT_ARG_TAKEN
@set TARGET_ROOT=%1
@goto TARGET_ROOT_IS_SET

:TARGET_ROOT_IS_SET



@if "%2"=="" goto PROJECT_NAME_ARG_NOT_TAKEN
@goto PROJECT_NAME_ARG_TAKEN

:PROJECT_NAME_ARG_NOT_TAKEN
@set PROJECT_NAME=%DEF_PROJECT_NAME%
@goto PROJECT_NAME_IS_SET

:PROJECT_NAME_ARG_TAKEN
@set PROJECT_NAME=%2
@goto PROJECT_NAME_IS_SET

:PROJECT_NAME_IS_SET


@set PROJECT_TARGET_ROOT=%TARGET_ROOT%/%PROJECT_NAME%


@echo PROJECT_TARGET_ROOT=%PROJECT_TARGET_ROOT%
@echo.
@echo.

